listen              1935;
max_connections     2000;

daemon              off;
srs_log_tank        console;
pid                 /var/run/srs.pid;

http_api {
    enabled         on;
    listen          127.0.0.1:1985;
}

http_server {
    enabled         off;
    listen          127.0.0.1:8080;
    dir             /usr/local/srs/objs/nginx/html;
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       ;
}

vhost __defaultVhost__ {
    # Оригинальный поток - БЕЗ HLS
    # Только транскодинг
    hls {
        enabled         off;
    }

    rtc {
        enabled     on;
        rtc_to_rtmp off;
    }

    transcode {
        enabled     on;
        ffmpeg      /usr/local/bin/ffmpeg;
        engine low360 {
            enabled         on;
            vcodec          libx264;
            vprofile        baseline;
            vpreset         veryfast;
            vfps            30;
            vbitrate        700;
            vwidth          640;
            vheight         360;
            acodec          aac;
            abitrate        96;
            asample_rate    44100;
            achannels       2;
            output          rtmp://127.0.0.1:[port]/[app]/[stream]_360?vhost=transcoded;
        }
    }

    play {
        gop_cache   on;
    }
}

# Отдельный vhost для транскодированного потока
vhost transcoded {
    hls {
        enabled         on;
        hls_path        /var/lib/srs/hls;
        hls_fragment    2;
        hls_window      6;
        hls_cleanup     on;
        hls_dispose     3;
        hls_wait_keyframe on;
        # Переименовать сегменты
        hls_m3u8_file   [app]/main.m3u8;
        hls_ts_file     [app]/main-[seq].ts;
    }

    play {
        gop_cache   on;
    }
}

