worker_processes  auto;
user              www-data;

error_log  /var/log/nginx-rtmp/error.log  warn;

pid        /run/nginx-rtmp.pid;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;

            exec_publish      /usr/bin/sudo /usr/local/bin/start-stream-services.sh $name;
            exec_publish_done /usr/bin/sudo /usr/local/bin/stop-stream-services.sh  $name;

            drop_idle_publisher 0;
        }

        application conf {
            live on;

            exec_publish      /usr/bin/sudo /usr/local/bin/start-stream-services.sh $name;
            exec_publish_done /usr/bin/sudo /usr/local/bin/stop-stream-services.sh  $name;

            drop_idle_publisher 0;
        }
    }
}
