#/usr/local/nginx/conf/nginx.conf

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name spoken-word.ru;

        location /live {
            root /srv/streaming;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        location /archive {
            root /srv/streaming;
            autoindex on;
            add_header Access-Control-Allow-Origin *;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;
        }
    }
}


# перезапуск nginx
# /usr/local/nginx/sbin/nginx -t && /usr/local/nginx/sbin/nginx -s reload
# sudo /usr/local/nginx/sbin/nginx -t && sudo /usr/local/nginx/sbin/nginx -s reload
