# nano /usr/local/nginx/conf/nginx.conf
worker_processes auto;

user  root;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name spoken-word.ru;

        # ►▶ HLS
        #   /live/…  →  /srv/streaming/live/…
        location /live/ {
            alias /srv/streaming/live/;        # <- alias, НЕ root
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;

            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t                    ts;
            }
        }

        # ►▶ Архив mp4
        #   /archive/…  →  /srv/streaming/archive/…
        location /archive/ {
            alias /srv/streaming/archive/;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        # ►▶ React‑frontend
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        # контроль обрывов (можно оставить дефолты)
        ping         30s;
        ping_timeout 15s;

        application live {
            live on;
	    exec_publish on;
            exec /usr/local/bin/start-hls.sh $app $name;

            # если нужен «автокик» после долгого отсутствия кадров
            drop_idle_publisher 15s;
        }
    }
}
